### ISSUE TITLE
don't ignore ascii case on BASE and PREFIX

### ISSUE THREAD

**Issue by andrefs** [oxigraph/rio#120]
Hello,

I was processing a graph where `base` was declared and used as a prefix. Example:

```turtle
@prefix base: <http://data.gesis.org/claimskg/> .
@prefix dcat: <http://www.w3.org/ns/dcat#> .

base:claimskg a dcat:Dataset .
```

This resulted in an `Unexpected char error` which I traced to here: https://github.com/oxigraph/rio/blob/main/turtle/src/turtle.rs#L278

If you check [Turtle's grammar specification](https://www.w3.org/TR/turtle/#grammar-production-base), it allows declaring a base IRI either with `@base` or `BASE`, but not lowercase `base`.

So maybe the case should not be ignored? (the same is valid for `PREFIX` btw)

Thanks!

**Comment by Tpt** [comment]
Hi! Thank you for trying Rio and reporting this bug!

> If you check [Turtle's grammar specification](https://www.w3.org/TR/turtle/#grammar-production-base), it allows declaring a base IRI either with `@base` or `BASE`, but not lowercase base.

Sadly, I don't think this is true. The note 1 just before the grammar states <q>Keywords in double quotes ("BASE", "PREFIX") are case-insensitive.</q>

However, because in this your example `base` is directly followed by `:` and the `PNAME_LN` rule of the grammar is supposed to be a "terminal" rule, the parser should be able to disambiguate and know that `base` is in this case a prefix and not the kewyord. This should be also the case if someone uses a `prefix:` or a `graph:` prefix.

**Comment by Tpt** [comment]
@andrefs I just release v0.8.2 that should fix this bug

**Comment by andrefs** [comment]
> Sadly, I don't think this is true. The note 1 just before the grammar states Keywords in double quotes ("BASE", "PREFIX") are case-insensitive.
Ah you're right I missed that!

Thank you so much for the super quick reply and fix! :+1:
