### ISSUE TITLE
TurtleParser throw several fake error

### ISSUE THREAD

**Issue by YruamaLairba** [oxigraph/rio#23]
Hi again,

Due to the issue i get yesterday, i decide to write a small program to test the Turtle parser by making it parse all ttl file of my computer. It found two kind of error that aren't, you can see corresponding file in tests/good_too of the joined archive. I also discovered a rdf test suit that i have tried, it also triggered error on some correct ttl file contained in tests/good of the joined archive.

The joined archive contain the project i used to do my tests.  It's just take path of the files to test in parameter and print the parse error when it's triggered. For example, `cargo run -- ls tests/*/*.tll` will parse all ttl file of the test suit.

PS: i know there is a `rio_testsuit` crate, but i wasn't able to use the binary

[test1.zip](https://github.com/Tpt/rio/files/4357206/test1.zip)

**Comment by Tpt** [comment]
Hi! Thank you for having a deeper look at Rio.

The `rio_testsuite` binary works only with the official test suite (the one in the `testsuite/rdf-tests` directory. But the crate tests runs both the official test suite and the one from Serd.

About the "good" serd tests (the ones you provide in the `good` directory), I have chosen to depart from them in three cases:
1. Not support the "ext-namedblank" extension that is not in the Turtle standard.
2. Validate IRIs after decoding. This way the parser only returns valid IRIs and don't require downstream tasks to validate them again if they want to ensure to only have valid IRIs. It makes the `#test-uri-escape` and `#test-escapes` fails. I believe it is a sensible choice because the RDF model requires IRIs to be valid IRIs.
3. Reject invalid UTF-8 code points instead of replacing them with a replacement character. I believe it follows better the Turtle spec that state that the file should be encoded in valid UTF-8. It makes the  `#test-out-of-range-unicode` test fail. But if it creates more harm than good, I could fairly easily change rio to use the replacement character instead (and maybe return a warning, this step requiring to add a warning system to Rio).

Thank you for your two additional tests.
* `blank_node_in_linebreak`: thank you for spotting the bug. It's related to the way Rio parsers does lookehead. I'm planning to work on a fix in the next few days.
* `two_hashtags_in_iri`: [according to RFC 3986](https://tools.ietf.org/html/rfc3986#appendix-A), `#` is not allowed in the URI fragment part. Allowing that would depart from the RDF 1.1 spec. [The WHATWAG URL standard](https://url.spec.whatwg.org/#fragment-state) seems to also forbid # in fragments.

**Comment by Tpt** [comment]
I just pushed a change that should fix all problems highlighted by `blank_node_in_linebreak`. I also added to the repository your test case. I'm planning to push a new release in the next few days. Sorry for the bug and thank you again for your feedbacks.

**Comment by Tpt** [comment]
This bug has been fixed in the released version 0.4.2. I believe I could close the issue.
