### ISSUE TITLE
Add another sentence or two in comment to explain the rational of stack size 128

### ISSUE THREAD

**Issue by thadguidry** [oxigraph/rio#76]
https://github.com/oxigraph/rio/blob/fd65f4ac1b7716eeff6bfbdc56d4848a66c2e575/turtle/src/lib.rs#L74

**Comment by thadguidry** [comment]
My feeling was there was a demonstrated performance benchmark somewhere or that cursory investigations of large public data led to this default of 128?  More info in the comment might be useful later on for others.

**Comment by Tpt** [comment]
I have not tested large public datasets. I have chosen 128 as a wet finger estimation of what should fit in a process stack. The limit is not here for performance but because the parser was crashing with a stack overflow error when they were too many nested structures. I found this crash while fuzzing the parser, I never head of anyone encountering the error in the wild (and I would not be very surprised if some other parsers also crashes on similar inputs).

This limit only applies to nested structures i.e. collections, anonymous blank nodes and RDF-star nested triples.
To say the truth I have never seen nested collections or anonymous blank nodes outside of some OWL ontologies definition. And there, I have never seen anything higher than 2 or 3.
For RDF-star, the thing is very new and there are not yet much datasets in the wild.
But maybe I am missing anything, if you know examples of significantly nested files, I would be very curious about them.

I'm going to update the constant comments with extra info.
